# packages in environment at C:\Users\Drustan\miniconda3\envs\cxr-cv:
#
# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bottleneck                1.3.5           py311h5bb9823_0  
bzip2                     1.0.8                he774522_0  
ca-certificates           2023.01.10           haa95532_0  
certifi                   2023.5.7        py311haa95532_0  
colorama                  0.4.6           py311haa95532_0  
cuda-cccl                 12.1.109                      0    nvidia
cuda-cudart               12.1.105                      0    nvidia
cuda-cudart-dev           12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-libraries-dev        12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvrtc-dev            12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.1.105                      0    nvidia
cuda-opencl-dev           12.1.105                      0    nvidia
cuda-profiler-api         12.1.105                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
debugpy                   1.5.1           py311hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
eigen                     3.3.7                h59b6b97_1  
executing                 0.8.3              pyhd3eb1b0_0  
ffmpeg                    4.2.2                he774522_0  
filelock                  3.9.0           py311haa95532_0  
freetype                  2.12.1               ha860e81_0  
giflib                    5.2.1                h8cc25b3_3  
glib                      2.69.1               h5dc1a3c_2  
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
hdf5                      1.10.6               h1756f20_1  
icc_rt                    2022.1.0             h6049295_2  
icu                       58.2                 ha925a31_3  
intel-openmp              2023.1.0         h59b6b97_46319  
ipykernel                 6.15.0             pyh025b116_0    conda-forge
ipython                   8.12.0          py311haa95532_0  
jedi                      0.18.1          py311haa95532_1  
jpeg                      9e                   h8ffe710_2    conda-forge
jupyter_client            8.1.0           py311haa95532_0  
jupyter_core              5.3.0           py311haa95532_0  
krb5                      1.19.4               h5b6d351_0  
lerc                      3.0                  hd77b12b_0  
libclang                  14.0.6          default_hb5a9fac_1  
libclang13                14.0.6          default_h8e68704_1  
libcublas                 12.1.0.26                     0    nvidia
libcublas-dev             12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufft-dev              11.0.2.4                      0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusolver-dev           11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libcusparse-dev           12.0.2.55                     0    nvidia
libdeflate                1.17                 h2bbff1b_0  
libffi                    3.4.4                hd77b12b_0  
libiconv                  1.16                 h2bbff1b_2  
libnpp                    12.0.2.50                     0    nvidia
libnpp-dev                12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 12.1.0.39                     0    nvidia
libnvjpeg-dev             12.1.0.39                     0    nvidia
libogg                    1.3.5                h2bbff1b_1  
libpng                    1.6.39               h8cc25b3_0  
libprotobuf               3.20.3               h23ce68f_0  
libsodium                 1.0.18               h62dcd97_0  
libtiff                   4.5.0                h6c2663c_2  
libuv                     1.44.2               h2bbff1b_0  
libvorbis                 1.3.7                he774522_0  
libwebp                   1.2.4                hbc33d0d_1  
libwebp-base              1.2.4                h2bbff1b_1  
libxml2                   2.10.3               h0ad7f3c_0  
libxslt                   1.1.37               h2bbff1b_0  
lz4-c                     1.9.4                h2bbff1b_0  
matplotlib-inline         0.1.6           py311haa95532_0  
mkl                       2023.1.0         h8bd8f75_46356  
mkl-service               2.4.0           py311h2bbff1b_1  
mkl_fft                   1.3.6           py311hf62ec03_1  
mkl_random                1.2.2           py311hf62ec03_1  
mpmath                    1.2.1           py311haa95532_0  
nest-asyncio              1.5.6           py311haa95532_0  
networkx                  2.8.4           py311haa95532_1  
numexpr                   2.8.4           py311h1fcbade_1  
numpy                     1.24.3          py311hdab7c0b_1  
numpy-base                1.24.3          py311hd01c5d8_1  
opencv                    4.6.0           py311heda8569_3  
openjpeg                  2.4.0                h4fc8c34_0  
openssl                   1.1.1t               h2bbff1b_0  
packaging                 23.0            py311haa95532_0  
pandas                    1.5.3           py311heda8569_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 hd77b12b_0  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0           py311hd77b12b_0  
pip                       23.0.1          py311haa95532_0  
platformdirs              2.5.2           py311haa95532_0  
prompt-toolkit            3.0.36          py311haa95532_0  
psutil                    5.9.0           py311h2bbff1b_0  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pydicom                   2.3.1              pyh1a96a4e_0    conda-forge
pygments                  2.15.1          py311haa95532_1  
python                    3.11.3               h966fe2a_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-gdcm               3.0.22                   pypi_0    pypi
pytorch                   2.1.0.dev20230526    py3.11_cpu_0    pytorch-nightly
pytorch-cuda              12.1                 hde6ce7c_5    pytorch-nightly
pytorch-mutex             1.0                         cpu    pytorch-nightly
pytz                      2022.7          py311haa95532_0  
pywin32                   305             py311h2bbff1b_0  
pyyaml                    6.0             py311h2bbff1b_1  
pyzmq                     25.0.2          py311hd77b12b_0  
qt-main                   5.15.2               he8e5bd7_8  
qt-webengine              5.15.9               hb9a9bb5_5  
qtwebkit                  5.212                h2bbfb41_5  
setuptools                67.8.0          py311haa95532_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
sympy                     1.11.1          py311haa95532_0  
tbb                       2021.8.0             h59b6b97_0  
tk                        8.6.12               h2bbff1b_0  
tornado                   6.2             py311h2bbff1b_0  
traitlets                 5.7.1           py311haa95532_0  
typing_extensions         4.5.0           py311haa95532_0  
tzdata                    2023c                h04d1e81_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.38.4          py311haa95532_0  
xz                        5.4.2                h8cc25b3_0  
yaml                      0.2.5                he774522_0  
zeromq                    4.3.4                hd77b12b_0  
zlib                      1.2.13               h8cc25b3_0  
zstd                      1.5.5                hd43e919_0  
